### ISSUE TITLE
NoClassDefFoundError when running on Server

### ISSUE THREAD

**Issue by TheLordofMelons** [iLexiconn/LLibraryLegacy#40]
When running this mod on a server it fails to find the javax/vecmath/Vector2f class.  This does not occur client side.  Even with no other mods installed it will always crash after the world loads.

```
---- Minecraft Crash Report ----
// But it works on my machine.

Time: 11/20/15 2:36 AM
Description: Ticking entity

java.lang.NoClassDefFoundError: javax/vecmath/Vector2f
    at net.ilexiconn.llibrary.common.ServerEventHandler.onEntityTick(ServerEventHandler.java:41)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_6_ServerEventHandler_onEntityTick_LivingUpdateEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:287)
    at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1560)
    at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:206)
    at net.minecraft.world.World.func_72866_a(World.java:2070)
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
    at net.minecraft.world.World.func_72870_g(World.java:2034)
    at net.minecraft.world.World.func_72939_s(World.java:1887)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.ClassNotFoundException: javax.vecmath.Vector2f
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(Unknown Source)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 17 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
    at net.ilexiconn.llibrary.common.ServerEventHandler.onEntityTick(ServerEventHandler.java:41)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_6_ServerEventHandler_onEntityTick_LivingUpdateEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:287)
    at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1560)
    at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:206)
    at net.minecraft.world.World.func_72866_a(World.java:2070)
    at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
    at net.minecraft.world.World.func_72870_g(World.java:2034)

-- Entity being ticked --
Details:
    Entity Type: Sheep (net.minecraft.entity.passive.EntitySheep)
    Entity ID: 0
    Entity Name: Sheep
    Entity's Exact location: -170.50, 80.00, 73.50
    Entity's Block location: World: (-171,80,73), Chunk: (at 5,5,9 in -11,4; contains blocks -176,0,64 to -161,255,79), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Entity's Momentum: 0.00, 0.00, 0.00
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:1887)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
    Level name: world
    All players: 0 total; []
    Chunk stats: ServerChunkCache: 625 Drop: 0
    Level seed: -479771348058155067
    Level generator: ID 00 - default, ver 1. Features enabled: true
    Level generator options: 
    Level spawn location: World: (-20,64,88), Chunk: (at 12,4,8 in -2,5; contains blocks -32,0,80 to -17,255,95), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Level time: 1 game time, 1 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 129010 (now: false), thunder time: 115291 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_67, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 251898328 bytes (240 MB) / 373817344 bytes (356 MB) up to 1908932608 bytes (1820 MB)
    JVM Flags: 2 total; -Xmx2G -XX:MaxPermSize=1G
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1566 4 mods loaded, 4 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
    UCHIJAAAA   FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1566-1.7.10-universal.jar) 
    UCHIJAAAA   Forge{10.13.4.1566} [Minecraft Forge] (forge-1.7.10-10.13.4.1566-1.7.10-universal.jar) 
    UCHIJAAAA   llibrary{0.5.5} [LLibrary] (llibrary-0.5.5-1.7.10.jar) 
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 0 / 20; []
    Is Modded: Definitely; Server brand changed to 'fml,forge'
    Type: Dedicated Server (map_server.txt)
```

**Comment by iLexiconn** [comment]
Uh, this is kinda strange. Maybe @gegy1000 can take a look at this?

**Comment by DanielleHuisman** [comment]
Was the server running on the same machine with the same Java version as the client you tried?

**Comment by pau101** [comment]
Servers don't use the vecmath library so it's not included. The only part of vanilla Minecraft that uses vecmath is shaders, which is for Matrix4f.

**Comment by Gegy** [comment]
@pau101, makes sense, I guess we could make our own class?

**Comment by pau101** [comment]
@gegy1000, That's what I've done previously in mods of mine.

**Comment by Gegy** [comment]
Fixed with latest commit. :)
